# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_libprogressbar', [dirname(__file__)])
        except ImportError:
            import _libprogressbar
            return _libprogressbar
        if fp is not None:
            try:
                _mod = imp.load_module('_libprogressbar', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _libprogressbar = swig_import_helper()
    del swig_import_helper
else:
    import _libprogressbar
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _libprogressbar.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _libprogressbar.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _libprogressbar.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _libprogressbar.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _libprogressbar.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _libprogressbar.SwigPyIterator_equal(self, x)

    def copy(self):
        return _libprogressbar.SwigPyIterator_copy(self)

    def next(self):
        return _libprogressbar.SwigPyIterator_next(self)

    def __next__(self):
        return _libprogressbar.SwigPyIterator___next__(self)

    def previous(self):
        return _libprogressbar.SwigPyIterator_previous(self)

    def advance(self, n):
        return _libprogressbar.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _libprogressbar.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _libprogressbar.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _libprogressbar.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _libprogressbar.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _libprogressbar.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _libprogressbar.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _libprogressbar.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class ivec(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ivec, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ivec, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _libprogressbar.ivec_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _libprogressbar.ivec___nonzero__(self)

    def __bool__(self):
        return _libprogressbar.ivec___bool__(self)

    def __len__(self):
        return _libprogressbar.ivec___len__(self)

    def __getslice__(self, i, j):
        return _libprogressbar.ivec___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _libprogressbar.ivec___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _libprogressbar.ivec___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _libprogressbar.ivec___delitem__(self, *args)

    def __getitem__(self, *args):
        return _libprogressbar.ivec___getitem__(self, *args)

    def __setitem__(self, *args):
        return _libprogressbar.ivec___setitem__(self, *args)

    def pop(self):
        return _libprogressbar.ivec_pop(self)

    def append(self, x):
        return _libprogressbar.ivec_append(self, x)

    def empty(self):
        return _libprogressbar.ivec_empty(self)

    def size(self):
        return _libprogressbar.ivec_size(self)

    def swap(self, v):
        return _libprogressbar.ivec_swap(self, v)

    def begin(self):
        return _libprogressbar.ivec_begin(self)

    def end(self):
        return _libprogressbar.ivec_end(self)

    def rbegin(self):
        return _libprogressbar.ivec_rbegin(self)

    def rend(self):
        return _libprogressbar.ivec_rend(self)

    def clear(self):
        return _libprogressbar.ivec_clear(self)

    def get_allocator(self):
        return _libprogressbar.ivec_get_allocator(self)

    def pop_back(self):
        return _libprogressbar.ivec_pop_back(self)

    def erase(self, *args):
        return _libprogressbar.ivec_erase(self, *args)

    def __init__(self, *args):
        this = _libprogressbar.new_ivec(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _libprogressbar.ivec_push_back(self, x)

    def front(self):
        return _libprogressbar.ivec_front(self)

    def back(self):
        return _libprogressbar.ivec_back(self)

    def assign(self, n, x):
        return _libprogressbar.ivec_assign(self, n, x)

    def resize(self, *args):
        return _libprogressbar.ivec_resize(self, *args)

    def insert(self, *args):
        return _libprogressbar.ivec_insert(self, *args)

    def reserve(self, n):
        return _libprogressbar.ivec_reserve(self, n)

    def capacity(self):
        return _libprogressbar.ivec_capacity(self)
    __swig_destroy__ = _libprogressbar.delete_ivec
    __del__ = lambda self: None
ivec_swigregister = _libprogressbar.ivec_swigregister
ivec_swigregister(ivec)

class dvec(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, dvec, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, dvec, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _libprogressbar.dvec_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _libprogressbar.dvec___nonzero__(self)

    def __bool__(self):
        return _libprogressbar.dvec___bool__(self)

    def __len__(self):
        return _libprogressbar.dvec___len__(self)

    def __getslice__(self, i, j):
        return _libprogressbar.dvec___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _libprogressbar.dvec___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _libprogressbar.dvec___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _libprogressbar.dvec___delitem__(self, *args)

    def __getitem__(self, *args):
        return _libprogressbar.dvec___getitem__(self, *args)

    def __setitem__(self, *args):
        return _libprogressbar.dvec___setitem__(self, *args)

    def pop(self):
        return _libprogressbar.dvec_pop(self)

    def append(self, x):
        return _libprogressbar.dvec_append(self, x)

    def empty(self):
        return _libprogressbar.dvec_empty(self)

    def size(self):
        return _libprogressbar.dvec_size(self)

    def swap(self, v):
        return _libprogressbar.dvec_swap(self, v)

    def begin(self):
        return _libprogressbar.dvec_begin(self)

    def end(self):
        return _libprogressbar.dvec_end(self)

    def rbegin(self):
        return _libprogressbar.dvec_rbegin(self)

    def rend(self):
        return _libprogressbar.dvec_rend(self)

    def clear(self):
        return _libprogressbar.dvec_clear(self)

    def get_allocator(self):
        return _libprogressbar.dvec_get_allocator(self)

    def pop_back(self):
        return _libprogressbar.dvec_pop_back(self)

    def erase(self, *args):
        return _libprogressbar.dvec_erase(self, *args)

    def __init__(self, *args):
        this = _libprogressbar.new_dvec(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _libprogressbar.dvec_push_back(self, x)

    def front(self):
        return _libprogressbar.dvec_front(self)

    def back(self):
        return _libprogressbar.dvec_back(self)

    def assign(self, n, x):
        return _libprogressbar.dvec_assign(self, n, x)

    def resize(self, *args):
        return _libprogressbar.dvec_resize(self, *args)

    def insert(self, *args):
        return _libprogressbar.dvec_insert(self, *args)

    def reserve(self, n):
        return _libprogressbar.dvec_reserve(self, n)

    def capacity(self):
        return _libprogressbar.dvec_capacity(self)
    __swig_destroy__ = _libprogressbar.delete_dvec
    __del__ = lambda self: None
dvec_swigregister = _libprogressbar.dvec_swigregister
dvec_swigregister(dvec)

class svec(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, svec, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, svec, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _libprogressbar.svec_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _libprogressbar.svec___nonzero__(self)

    def __bool__(self):
        return _libprogressbar.svec___bool__(self)

    def __len__(self):
        return _libprogressbar.svec___len__(self)

    def __getslice__(self, i, j):
        return _libprogressbar.svec___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _libprogressbar.svec___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _libprogressbar.svec___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _libprogressbar.svec___delitem__(self, *args)

    def __getitem__(self, *args):
        return _libprogressbar.svec___getitem__(self, *args)

    def __setitem__(self, *args):
        return _libprogressbar.svec___setitem__(self, *args)

    def pop(self):
        return _libprogressbar.svec_pop(self)

    def append(self, x):
        return _libprogressbar.svec_append(self, x)

    def empty(self):
        return _libprogressbar.svec_empty(self)

    def size(self):
        return _libprogressbar.svec_size(self)

    def swap(self, v):
        return _libprogressbar.svec_swap(self, v)

    def begin(self):
        return _libprogressbar.svec_begin(self)

    def end(self):
        return _libprogressbar.svec_end(self)

    def rbegin(self):
        return _libprogressbar.svec_rbegin(self)

    def rend(self):
        return _libprogressbar.svec_rend(self)

    def clear(self):
        return _libprogressbar.svec_clear(self)

    def get_allocator(self):
        return _libprogressbar.svec_get_allocator(self)

    def pop_back(self):
        return _libprogressbar.svec_pop_back(self)

    def erase(self, *args):
        return _libprogressbar.svec_erase(self, *args)

    def __init__(self, *args):
        this = _libprogressbar.new_svec(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _libprogressbar.svec_push_back(self, x)

    def front(self):
        return _libprogressbar.svec_front(self)

    def back(self):
        return _libprogressbar.svec_back(self)

    def assign(self, n, x):
        return _libprogressbar.svec_assign(self, n, x)

    def resize(self, *args):
        return _libprogressbar.svec_resize(self, *args)

    def insert(self, *args):
        return _libprogressbar.svec_insert(self, *args)

    def reserve(self, n):
        return _libprogressbar.svec_reserve(self, n)

    def capacity(self):
        return _libprogressbar.svec_capacity(self)
    __swig_destroy__ = _libprogressbar.delete_svec
    __del__ = lambda self: None
svec_swigregister = _libprogressbar.svec_swigregister
svec_swigregister(svec)

class ProgressBar(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ProgressBar, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ProgressBar, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _libprogressbar.new_ProgressBar(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _libprogressbar.delete_ProgressBar
    __del__ = lambda self: None

    def set_level(self, level):
        return _libprogressbar.ProgressBar_set_level(self, level)

    def counter(self):
        return _libprogressbar.ProgressBar_counter(self)

    def progress(self, *args):
        return _libprogressbar.ProgressBar_progress(self, *args)

    def __iadd__(self, step):
        return _libprogressbar.ProgressBar___iadd__(self, step)

    def __call__(self, *args):
        return _libprogressbar.ProgressBar___call__(self, *args)
ProgressBar_swigregister = _libprogressbar.ProgressBar_swigregister
ProgressBar_swigregister(ProgressBar)

class NoProgressBar(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, NoProgressBar, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, NoProgressBar, name)
    __repr__ = _swig_repr

    def __call__(self, arg2, arg3):
        return _libprogressbar.NoProgressBar___call__(self, arg2, arg3)

    def __init__(self):
        this = _libprogressbar.new_NoProgressBar()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _libprogressbar.delete_NoProgressBar
    __del__ = lambda self: None
NoProgressBar_swigregister = _libprogressbar.NoProgressBar_swigregister
NoProgressBar_swigregister(NoProgressBar)

# This file is compatible with both classic and new-style classes.


